# 1 - Download & Install Python 3
FROM python:3.13.2-slim-bullseye

# setup linux os packages

# 2 - Create Virtual Environment
# 3 - Install Python Packages - `pip install <package-name>`

# Create a virtual environment
RUN python -m venv /opt/venv

# Set the virtual environment as the current location
ENV PATH=/opt/venv/bin:$PATH

# Upgrade pip
RUN pip install --upgrade pip

# Set Python-related environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install os dependencies for our mini vm
RUN apt-get update && apt-get install -y \
    # for postgres
    libpq-dev \
    # for Pillow
    libjpeg-dev \
    # for CairoSVG
    libcairo2 \
    # other
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Create our application directory
RUN mkdir -p /app

# Set the working directory to that app directory
WORKDIR /app

# 1. Copy ONLY the requirements file first
# The '.' means copy to WORKDIR (so /app/requirements.txt)
COPY requirements.txt .

# 2. Install requirements
# This layer will now be cached unless requirements.txt changes
RUN pip install -r requirements.txt

# 3. NOW copy the project source code
# This copies the local 'src' folder to '/app/src'
COPY ./src ./src

# Clean up apt cache to reduce image size
RUN apt-get remove --purge -y \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*